<?php // @codingStandardsIgnoreFile
$collection = $block->getBanners();
$mediaurl = $block->mediaurl();
?>
<div class="owl-slider">
<div id="carousel" class="owl-carousel">

<?php foreach ($collection as $item) {
    $banner_status = $item->getData("status");
    if ($banner_status) { ?>
<div class="item">
  <img src="<?php echo $mediaurl .
      "mageget_slider/" .
      $item->getData("image"); ?>">
</div>

  <?php }
} ?>
</div>
</div>